spring:
  application:
    name: security

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true


